// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTransfer(arg1) {
  return window['go']['app']['App']['CancelTransfer'](arg1);
}

export function ChooseFolder() {
  return window['go']['app']['App']['ChooseFolder']();
}

export function DeleteSharedFile(arg1) {
  return window['go']['app']['App']['DeleteSharedFile'](arg1);
}

export function GeneratePairingPIN() {
  return window['go']['app']['App']['GeneratePairingPIN']();
}

export function GetDevices() {
  return window['go']['app']['App']['GetDevices']();
}

export function GetHistory(arg1) {
  return window['go']['app']['App']['GetHistory'](arg1);
}

export function GetSharedFiles(arg1) {
  return window['go']['app']['App']['GetSharedFiles'](arg1);
}

export function GetState() {
  return window['go']['app']['App']['GetState']();
}

export function GetTransfers() {
  return window['go']['app']['App']['GetTransfers']();
}

export function OpenSharedFolder() {
  return window['go']['app']['App']['OpenSharedFolder']();
}

export function Pair(arg1, arg2) {
  return window['go']['app']['App']['Pair'](arg1, arg2);
}

export function RemovePeer(arg1) {
  return window['go']['app']['App']['RemovePeer'](arg1);
}

export function SendFile(arg1, arg2, arg3) {
  return window['go']['app']['App']['SendFile'](arg1, arg2, arg3);
}

export function SetSharedDir(arg1) {
  return window['go']['app']['App']['SetSharedDir'](arg1);
}
