// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {peers} from '../models';
import {history} from '../models';
import {filesystem} from '../models';
import {transfer} from '../models';

export function CancelTransfer(arg1:string):Promise<void>;

export function ChooseFolder():Promise<string>;

export function DeleteSharedFile(arg1:string):Promise<void>;

export function GeneratePairingPIN():Promise<string>;

export function GetDevices():Promise<Array<peers.Peer>>;

export function GetHistory(arg1:number):Promise<Array<history.Entry>>;

export function GetSharedFiles(arg1:string):Promise<Array<filesystem.FileItem>>;

export function GetState():Promise<Record<string, any>>;

export function GetTransfers():Promise<Array<transfer.Transfer>>;

export function OpenSharedFolder():Promise<void>;

export function Pair(arg1:string,arg2:string):Promise<void>;

export function RemovePeer(arg1:string):Promise<void>;

export function SendFile(arg1:string,arg2:string,arg3:string):Promise<transfer.Transfer>;

export function SetSharedDir(arg1:string):Promise<void>;
