// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseFolder():Promise<string>;

export function GetState():Promise<Record<string, any>>;

export function OpenSharedFolder():Promise<void>;

export function Pair(arg1:string,arg2:string):Promise<void>;

export function RemovePeer(arg1:string):Promise<void>;

export function SetSharedDir(arg1:string):Promise<void>;
