// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseFolder() {
  return window['go']['main']['App']['ChooseFolder']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function OpenSharedFolder() {
  return window['go']['main']['App']['OpenSharedFolder']();
}

export function Pair(arg1, arg2) {
  return window['go']['main']['App']['Pair'](arg1, arg2);
}

export function RemovePeer(arg1) {
  return window['go']['main']['App']['RemovePeer'](arg1);
}

export function SetSharedDir(arg1) {
  return window['go']['main']['App']['SetSharedDir'](arg1);
}
